# Generated by Django 4.2.7 on 2023-11-30 06:41

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0003_alter_category_slug_category_unique_parent_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="CartPromo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128, verbose_name="наименование правила на корзину")),
                ("items_from", models.IntegerField(verbose_name="кол-во товаров в корзине от")),
                ("items_to", models.IntegerField(verbose_name="кол-во товаров в корзине до")),
                (
                    "price_from",
                    models.DecimalField(decimal_places=2, max_digits=12, verbose_name="общая стоимость корзины от"),
                ),
                (
                    "price_to",
                    models.DecimalField(decimal_places=2, max_digits=12, verbose_name="общая стоимость корзины до"),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                        verbose_name="размер скидки в рублях",
                    ),
                ),
            ],
            options={
                "verbose_name": "правило скидки на корзину",
                "verbose_name_plural": "правила скидок на корзину",
            },
        ),
        migrations.CreateModel(
            name="SetPromo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128, verbose_name="наименование набора")),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                        verbose_name="размер скидки в рублях",
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        related_name="categories_set",
                        to="products.category",
                        verbose_name="набор категорий",
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True, related_name="products_set", to="products.product", verbose_name="набор товаров"
                    ),
                ),
            ],
            options={
                "verbose_name": "правило скидки на набор",
                "verbose_name_plural": "правило скидок на набор",
            },
        ),
        migrations.CreateModel(
            name="Promo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128, verbose_name="наименование скидки")),
                ("description", models.TextField(max_length=1024, verbose_name="описание скидки")),
                (
                    "value",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="размер скидки в процентах",
                    ),
                ),
                (
                    "weight",
                    models.FloatField(
                        unique=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.01),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                        verbose_name="вес скидки",
                    ),
                ),
                ("active_from", models.DateTimeField(verbose_name="действует от ")),
                ("active_to", models.DateTimeField(verbose_name="действует до ")),
                (
                    "carts",
                    models.ManyToManyField(
                        blank=True, related_name="promos", to="discount.cartpromo", verbose_name="правила на корзину"
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True, related_name="promos", to="products.category", verbose_name="категории"
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True, related_name="promos", to="products.product", verbose_name="товары"
                    ),
                ),
                (
                    "sets",
                    models.ManyToManyField(
                        blank=True, related_name="promos", to="discount.setpromo", verbose_name="наборы"
                    ),
                ),
            ],
            options={
                "verbose_name": "скидка",
                "verbose_name_plural": "скидки",
            },
        ),
    ]
