# Generated by Django 4.2.7 on 2023-11-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserOfferCart",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.IntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "запись корзины",
                "verbose_name_plural": "записи корзины",
            },
        ),
    ]
