# Generated by Django 4.2.7 on 2023-11-20 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("shops", "0001_initial"),
        ("cart", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="useroffercart",
            name="offer",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="shops.offer"),
        ),
        migrations.AddField(
            model_name="useroffercart",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="carts", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
